### ISSUE TITLE
Safari and fetch() request

### ISSUE THREAD

**Issue by sweetppro** [xavcz/nova-forms-upload#4]
to get this working on Safari is quite simple.
1. I installed the [fetch](https://github.com/github/fetch) package like so:
    `npm install whatwg-fetch --save`
2. Add this line in Upload.jsx:
    `import 'whatwg-fetch'`

**Comment by xavxyz** [comment]
Thanks @sweetppro, I'll use `isomorphic-fetch` 👍  https://www.npmjs.com/package/isomorphic-fetch

>See Matt Andrews' isomorphic-fetch for isomorphic usage (exports node-fetch for server-side, whatwg-fetch for client-side).
