### ISSUE TITLE
what exactly i need to fill in settings.json

### ISSUE THREAD

**Issue by iammini5** [xavcz/nova-forms-upload#7]
it is not clear what to put in below, what is YOUR_APP_NAME ? 
BTW i don't see any code in vulcan-forms-upload uses present name  ?

  "cloudinaryCloudName": "YOUR_APP_NAME",
  "cloudinaryPresets": {
    "avatar": "YOUR_PRESET_ID",
    "posts": "THE_SAME_OR_ANOTHER_PRESET_ID"
  }

**Comment by xavxyz** [comment]
`YOUR_APP_NAME` is the cloudname you create on Cloudinary

This is use internally by cloudinary to send your files there

The other presets are used when you define your custom fields: https://github.com/xavcz/vulcan-forms-upload/#image-for-posts

And btw, this package is used internally in Vulcan, you should file an issue there if you run into troubles.
