### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by wizidot** [xavcz/nova-forms-upload#8]
Hi,
This package is awsome but it's not compatible withe the last release of React (16+). To prevent some issues with proptypes you need to import the prop-types package as described here : 
https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

 
.meteor\packages\vulcan_forms-upload\1.3.2\web.browser\lib\Upload.jsx
.meteor\packages\vulcan_forms-upload\1.3.2\os\lib\Upload.jsx
.meteor\packages\vulcan_forms-upload\1.3.2\web.cordova\lib\Upload.jsx
```javascript
import { Components, getSetting, registerComponent } from 'meteor/vulcan:lib';
import React, { Component } from 'react';
import Dropzone from 'react-dropzone';
import PropTypes from 'prop-types';
```
[...]
```javascript
Upload.propTypes = {
  name: PropTypes.string,
  value: PropTypes.any,
  label: PropTypes.string
};

Upload.contextTypes = {
  addToAutofilledValues: PropTypes.func,
}
```

**Comment by xavxyz** [comment]
Hey @wizidot !

This package is now part of vulcan's core 👍 

https://github.com/VulcanJS/Vulcan/tree/master/packages/vulcan-forms-upload

Thanks for reporting, open an issue there!
